### ISSUE TITLE
Doesn't build with DXIL2SPIRV

### ISSUE THREAD

**Issue by isaboll1** [HansKristian-Work/vkd3d-standalone#1]
when building using msys2, the cmake build does not include dxil-spirv, even though it's a sub project that's in the vkd3d repo like "SPIR-V Headers" and "Vulkan Headers"

**Comment by HansKristian-Work** [comment]
It needs to be linked through as a separate module with CMake, but either way this repo is obsolete now that the main repo has Meson, and this repo is mostly just for my personal use right now.
